If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 要終止批次工作嗎 (Y/N)? 

(mri) D:\MRI\brats3d>